### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by Highstrike** [joshuapaling/CakePHP-Combinator-Plugin#7]
I noticed your plugin is deprecated and you're telling people to check out Mark Story's AssetCompress Plugin. I tried that and it seemed too complicated + missing the build automatically feature, i'm not going to use cake bake every time i change a javascript file geez :)

So, i wrote my own. You can check it out here: https://github.com/Highstrike/cakephp-compressor It is very similar to yours but uses some classes from mrclay's minify project, more specifically google closure for js and it can also do HTML minification. It's very straight forward.

I would appreciate if you could recommend my Compressor somewhere in your readme file, It might help out people in the future :+1:

**Comment by joshuapaling** [comment]
Done, thanks.
